language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-22.0.1
    - android-22
    - add-on
    - extra
before_install:
  - cd android
script: 
  - ./gradlew test --info
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/